# -*- coding: utf-8 -*-
"""HW_02_03_prompt engineering_Erfan Eslamieh

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xysZeFE01D4vosHqlrxt28ltYT45yci8
"""

# Commented out IPython magic to ensure Python compatibility.
!pip install -q  langchain-openai langchain_community tiktoken langchain
# !pip install -q  langchain-cohere
# %pip install -qU langchain-google-genai

"""***Import Libraries***"""

import os
from langchain.prompts import PromptTemplate
from langchain_google_genai import ChatGoogleGenerativeAI

"""***If we use Open ai the code below can help us***"""

# import os
# from google.colab import userdata
# if "OPENAI_API_KEY" not in os.environ:

#     os.environ["OPENAI_API_KEY"] =  userdata.get('Openai_api_key')

# from langchain_openai import ChatOpenAI

# MODEL_NAME = "gpt-4o-mini"  # Ensure you use a valid OpenAI model name
# llm = ChatOpenAI(model_name=MODEL_NAME, temperature=0, max_tokens=512)

# print(f"Using model: {llm.model_name}")

from google.colab import userdata
if "GOOGLE_API_KEY" not in os.environ:
    os.environ["GOOGLE_API_KEY"] =  userdata.get('GOOGLE_API_KEY')

os.environ["GOOGLE_API_KEY"] = "AIzaSyBniRQ8VnJZVPGMdvImryK7R0NsAVSqxX0"

llm = ChatGoogleGenerativeAI(
    temperature=0,
    model="gemini-2.0-flash-exp"
)

"""---

**We want to see the below information for this resume in English:**

- Full Name
- Email
- Phone Number
- Education (Degree, Field, University, Graduation Year)
- Work Experience (Job Title, Company, Duration, Key Responsibilities)
- Skills
- Certifications and Training

---

**First we need to read resume file so we import it**

**put the resume file in directory of google colab**
"""

with open("resume_sample1.txt", "r", encoding="utf-8") as file:
    resume_sample1 = file.read()

"""**Now it's time to make prompt for creating a zero shot model**"""

prompt_zero_en = f"""
Extract the following information from the resume below.
- Email
- Phone Number
- Education (Degree, Field, University, Graduation Year)
- Work Experience (Job Title, Company, Duration, Key Responsibilities)
- Skills
- Certifications and Training


Please extract the following information from the resume and provide the output in an unstructured json format.

Resume:
{resume_sample1}
"""

response_1 = llm.invoke(prompt_zero_en)
print(response_1.content)

prompt_few_en = f"""
You are a data extractor. Your job is to read a resume and return the extracted information in a valid JSON format **exactly** following the structure shown in the example below.


Extract the following information from the resume below:
- Email
- Phone Number
- Education (Degree, Field, University, Graduation Year)
- Work Experience (Job Title, Company, Duration, Key Responsibilities)
- Skills
- Certifications


Here is the structure you must follow:

{{
  "Full Name": "Full name here",
  "Email": "email@example.com",
  "Phone Number": "+xx xxx xxx xxxx",
  "Education": [
    {{
      "Degree": "e.g., MSc",
      "Field": "e.g., Data Science",
      "University": "e.g., University of Tehran",
      "Graduation Year": 2021
    }}
  ],
  "Work Experience": [
    {{
      "Job Title": "e.g., Data Scientist",
      "Company": "e.g., Snapp",
      "Duration": "e.g., 2022–Present",
      "Key Responsibilities": [
        "Responsibility 1",
        "Responsibility 2"
      ]
    }}
  ],
  "Skills": [
    "Skill 1",
    "Skill 2"
  ],
  "Certifications": [
    "Certification 1",
    "Certification 2"
  ]
}}

Now, extract the information from the resume below and return only a valid JSON with no extra explanation. The values should be correct and placed in the correct structure.

Important: All numeric values (such as "Graduation Year") must be returned as **integers**, NOT strings. Do NOT put quotation marks around numbers.

Return only clean and valid JSON. No explanation or extra text.

Resume:
{resume_sample1}
"""

response_2 = llm.invoke(prompt_zero_en)
print(response_2.content)

"""**ما می‌خواهیم اطلاعات زیر را برای این رزومه به زبان فارسی بنویسیم:**"""

with open("resume_sample2.txt", "r", encoding="utf-8") as file:
    resume_sample2 = file.read()

prompt_zero_fr = f"""
اطلاعات زیر را از رزومه زیر استخراج کنید.
- ایمیل
- شماره تلفن
- تحصیلات (مدرک، رشته، دانشگاه، سال فارغ التحصیلی)
- تجربیات شغلی (عنوان شغلی، شرکت، مدت زمان، مسئولیت‌های کلیدی)
- مهارت‌ها
- گواهینامه‌ها و دوره های آموزشی


خروجی رزومه با فرمت غیر ساختاریافته json باشه
رزومه:
{resume_sample2}"""

response_3 = llm.invoke(prompt_zero_fr)
print(response_3.content)

"""**خروجی فایل json برای فایل بالا  بصورت ساختار یافته نبوده جون عتناوین به انگلیسی و همر موضوع به فارسی نوشته شده**"""

prompt_few_fr = f"""
شما یک مدل استخراج‌گر اطلاعات هستید. وظیفه‌ی شما این است که از رزومه‌ زیر اطلاعات مشخص‌شده را استخراج کرده و خروجی را دقیقاً به‌صورت JSON و با ساختار زیر و **با کلیدهای فارسی** ارائه دهید.

اطلاعات مورد نیاز شامل:
- ایمیل
- شماره تلفن
- تحصیلات (مدرک، رشته، دانشگاه، سال فارغ‌التحصیلی)
- سوابق کاری (عنوان شغلی، شرکت، مدت زمان، مسئولیت‌ها)
- مهارت‌ها
- گواهی‌نامه‌ها و دوره‌های آموزشی

در ادامه یک نمونه از ساختار JSON را مشاهده می‌کنید که دقیقاً باید از همان پیروی شود:

{{
  "ایمیل": "example@example.com",
  "شماره تلفن": "۰۹۱۲۱۲۳۴۵۶۷",
  "تحصیلات": [
    {{
      "مدرک": "کارشناسی ارشد",
      "رشته": "علوم کامپیوتر",
      "دانشگاه": "دانشگاه تهران",
      "سال فارغ‌التحصیلی": ۱۴۰۰
    }}
  ],
  "سوابق کاری": [
    {{
      "عنوان شغلی": "توسعه‌دهنده نرم‌افزار",
      "شرکت": "شرکت فناوران هوشمند",
      "مدت زمان": "۱۳۹۹ تا ۱۴۰۲",
      "مسئولیت‌ها": [
        "توسعه‌ی نرم‌افزارهای تحت وب",
        "طراحی پایگاه داده"
      ]
    }}
  ],
  "مهارت‌ها": [
    "پایتون",
    "SQL",
    "یادگیری ماشین"
  ],
  "گواهی‌نامه‌ها و دوره‌های آموزشی": [
    "مدرک یادگیری عمیق از دانشگاه استنفورد",
    "دوره‌ی تحلیل داده‌های پیشرفته گوگل"
  ]
}}

حالا اطلاعات زیر را از رزومه‌ی داده‌شده استخراج کرده و دقیقاً به همین شکل و فقط به‌صورت JSON فارسی بازگردانید. هیچ توضیحی اضافه نکنید.

رزومه:
{resume_sample2}
"""

response_4 = llm.invoke(prompt_few_fr)
print(response_4.content)

"""**خروجی فایل json در بالا با انسجام بیشتر و خیلی ساختاریافته تر از مدل اولی برای رزومه فارسی است چون تمامی عناوین همراه با مقادیر آن به فارسی طبق الگویی که برایش تعریف کردیم به زبان فارسی نوشته شده است**"""

