# -*- coding: utf-8 -*-
"""HW_02_01_prompt engineering_Erfan Eslamieh

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GvRA2m082yx38MbSl1Y1-lM95pzxELt6

***تمرین اول:  بررسی اثر جزئیات پرامپت بر کیفیت محتوای تولید شده***

***Exercise One: Examining the Effect of Prompt Details on the Quality of Produced Content***
"""

# Commented out IPython magic to ensure Python compatibility.
!pip install -q  langchain-openai langchain_community tiktoken langchain
# !pip install -q  langchain-cohere
# %pip install -qU langchain-google-genai

"""***If we use Open ai the code below can help us***"""

# import os
# from google.colab import userdata
# if "OPENAI_API_KEY" not in os.environ:

#     os.environ["OPENAI_API_KEY"] =  userdata.get('Openai_api_key')

# from langchain_openai import ChatOpenAI

# MODEL_NAME = "gpt-4o-mini"  # Ensure you use a valid OpenAI model name
# llm = ChatOpenAI(model_name=MODEL_NAME, temperature=0, max_tokens=512)

# print(f"Using model: {llm.model_name}")

"""#### But we use actually gemini for this Task"""

from google.colab import userdata
if "GOOGLE_API_KEY" not in os.environ:
    os.environ["GOOGLE_API_KEY"] =  userdata.get('google_api_key')

from langchain_google_genai import ChatGoogleGenerativeAI

llm = ChatGoogleGenerativeAI(
    model="gemini-2.0-flash-exp",
    temperature=0,
    max_tokens=None,
    timeout=None,
    max_retries=2,
    # other params...
)

from google.colab import userdata
if "GOOGLE_API_KEY" not in os.environ:
    os.environ["GOOGLE_API_KEY"] =  userdata.get('GOOGLE_API_KEY')

"""### Import Libraries"""

import os
from langchain.prompts import PromptTemplate
from langchain_google_genai import ChatGoogleGenerativeAI

"""***تمرین اول با پرامپت به زبان فارسی***

---

***باتوجه به رشته من یعنی علوم شناختی موضوع انتخابی من به شرح زیر است:***


**کاربرد شبکه‌های عصبی مصنوعی در مدل‌سازی فرآیندهای شناختی مغز انسان**

---

### Template 1

**پرامپت ۱ - کلی و بدون جزئیات**

####پرامپت ها و موضوع و وظیفه اصلی در تمپلیت 1 بصورت عادی و پشت سر هم تعریف شده است
"""

os.environ["GOOGLE_API_KEY"] = "AIzaSyBniRQ8VnJZVPGMdvImryK7R0NsAVSqxX0"

llm = ChatGoogleGenerativeAI(
    temperature=0,
    model="gemini-2.0-flash-exp"
)

template_1 = """
فرض کن تو یک مقاله‌نویس علمی و حرفه ای هستی که در حوزه‌ی علوم اعصاب و هوش مصنوعی تخصص داری.
وظیفه‌ی تو نوشتن مقاله‌ای درباره‌ی موضوع زیر است:

موضوع: کاربرد شبکه‌های عصبی مصنوعی در مدل‌سازی فرآیندهای شناختی مغز انسان

پرامپت:
یک مقاله درباره‌ی کاربرد شبکه‌های عصبی مصنوعی در مدل‌سازی فرآیندهای شناختی مغز انسان بنویس.
"""

prompt = PromptTemplate.from_template(template_1)

formatted_prompt = prompt.format()

response = llm.invoke(formatted_prompt)
print(response.content)

"""**پرامپت 1 - اینبار پرامپت اول رو با تعریف متغیر هایی برای تفکیک پرامپت ها
مینویسیم**
"""

template_1 = """
تو یک مقاله‌نویس علمی و حرفه ای هستی که در حوزه‌ی {field} تخصص داری
وظیفه‌ی تو نوشتن مقاله‌ای درباره‌ی موضوع زیر است:

موضوع: {topic}

پرامپت: {task}
"""

prompt = PromptTemplate(input_variables=["field", "topic", "task"], template=template_1)

field = "علوم اعصاب و هوش مصنوعی"
topic = "کاربرد شبکه‌های عصبی مصنوعی در مدل‌سازی فرآیندهای شناختی مغز انسان"
task = "یک مقاله درباره‌ی کاربرد شبکه‌های عصبی مصنوعی در مدل‌سازی فرآیندهای شناختی مغز انسان بنویس"

formatted_prompt = prompt.format(field=field, topic=topic, task=task)

print(formatted_prompt)

response = llm.invoke(formatted_prompt)
print(response.content)

"""###Template 2

**پرامپت 2 - با مشخص کردن بخش های اصلی هر پرامپت**

#### پرامپت ها و موضوع و وظیفه اصلی در تمپلیت 2 بصورت عادی و پشت سر هم تعریف شده است
"""

template_2_1 = """
تو یک مقاله‌نویس علمی و حرفه ای هستی که در حوزه‌ی علوم اعصاب و هوش مصنوعی تخصص داری.
وظیفه‌ی تو نوشتن مقاله‌ای درباره‌ی موضوع زیر است:

موضوع: کاربرد شبکه‌های عصبی مصنوعی در مدل‌سازی فرآیندهای شناختی مغز انسان

پرامپت:
یک مقاله‌ی علمی درباره‌ی کاربرد شبکه‌های عصبی مصنوعی در مدل‌سازی فرآیندهای شناختی مغز انسان بنویس.
مقاله باید شامل بخش‌های زیر باشد:
- مقدمه
- معرفی انواع شبکه‌های عصبی مصنوعی
- نحوه‌ی مدل‌سازی فرایندهای شناختی
- مزایا و محدودیت‌ها
- نتیجه‌گیری

**توجه:** مقاله نباید شامل فهرست منابع یا ارجاع به منابع باشد.

"""
prompt = PromptTemplate.from_template(template_2_1)

formatted_prompt_2_1 = prompt.format()

response_2_1 = llm.invoke(formatted_prompt_2_1)
print(response_2_1.content)

"""**پرامپت 2 - اینبار پرامپت دوم رو هم با تعریف متغیر هایی برای تفکیک پرامپت ها مینویسیم**"""

template_2_2 = """
تو یک مقاله‌نویس علمی و حرفه ای هستی که در حوزه‌ی {field} تخصص داری.
وظیفه‌ی تو نوشتن مقاله‌ای درباره‌ی موضوع زیر است:

موضوع: {topic}

پرامپت: {task} """

prompt = PromptTemplate(
    input_variables=["field", "topic", "task"],
    template=template_2_2
)

field = "علوم اعصاب و هوش مصنوعی"
topic = "کاربرد شبکه‌های عصبی مصنوعی در مدل‌سازی فرآیندهای شناختی مغز انسان"
task = """یک مقاله‌ی علمی درباره‌ی کاربرد شبکه‌های عصبی مصنوعی در مدل‌سازی فرآیندهای شناختی مغز انسان بنویس.
مقاله باید شامل بخش‌های زیر باشد:
- مقدمه
- معرفی انواع شبکه‌های عصبی مصنوعی
- نحوه‌ی مدل‌سازی فرایندهای شناختی
- مزایا و محدودیت‌ها
- نتیجه‌گیری

**توجه:** مقاله نباید شامل فهرست منابع یا ارجاع به منابع باشد.

"""

formatted_prompt_2_2 = prompt.format(field=field, topic=topic, task=task)

response_2_2 = llm.invoke(formatted_prompt_2_2)
print(response_2_2.content)

"""#### Template 3

###پرامپت ها و موضوع و وظیفه اصلی در تمپلیت 3 بصورت عادی و پشت سر هم تعریف شده است

**پرامپت 3 - با جزئیات خیلی دقیقتر و تعریف و مشخص کردن تیتر هر عنوان برای توضیح مدل**
"""

template_3_1 = """
تو یک مقاله‌نویس علمی و حرفه ای هستی که در حوزه‌ی علوم اعصاب و هوش مصنوعی تخصص داری.
وظیفه‌ی تو نوشتن مقاله‌ای درباره‌ی موضوع زیر است:

موضوع: کاربرد شبکه‌های عصبی مصنوعی در مدل‌سازی فرآیندهای شناختی مغز انسان

پرامپت:
یک مقاله‌ی علمی درباره‌ی کاربرد شبکه‌های عصبی مصنوعی در مدل‌سازی فرآیندهای شناختی مغز انسان بنویس.
مقاله باید شامل بخش‌های زیر باشد:

- مقدمه: تعریف علوم اعصاب شناختی و اهمیت مدل‌سازی شناخت با استفاده از هوش مصنوعی
- معرفی مدل‌های شبکه‌ی عصبی: معرفی RNN، LSTM، و Transformer و نحوه‌ی شباهت آن‌ها با مغز
- مدل‌سازی کارکردهای شناختی:
   - حافظه‌ی کاری با LSTM
   - توجه انتخابی با مکانیزم attention
   - تصمیم‌گیری با یادگیری تقویتی
- مزایا و چالش‌ها:
   - مزایا: تطبیق‌پذیری بالا، یادگیری غیرخطی، شباهت عملکردی با مغز
   - چالش‌ها: تفسیرناپذیری، تفاوت ساختار زیستی با معماری شبکه‌ها، نیاز به داده‌ی زیاد
- نتیجه‌گیری: خلاصه‌ی نکات کلیدی و آینده‌ی تعامل بین علوم اعصاب و هوش مصنوعی

**توجه:** مقاله باید شامل فهرست منابع یا ارجاع به منابع باشد.

"""
prompt = PromptTemplate.from_template(template_3_1)

formatted_prompt_3_1 = prompt.format()

response_3_1 = llm.invoke(formatted_prompt_3_1)
print(response_3_1.content)

"""**پرامپت 3- اینبار پرامپت سوم رو هم با تعریف متغیر هایی برای تفکیک پرامپت ها مینویسیم**"""

template_3_2 = """
تو یک مقاله‌نویس علمی و حرفه ای هستی که در حوزه‌ی {field} تخصص داری.
وظیفه‌ی تو نوشتن مقاله‌ای درباره‌ی موضوع زیر است:

موضوع: {topic}

پرامپت:
{task}
"""

prompt = PromptTemplate(
    input_variables=["field", "topic", "task"],
    template=template_3_2
)

field = "علوم اعصاب و هوش مصنوعی"
topic = "کاربرد شبکه‌های عصبی مصنوعی در مدل‌سازی فرآیندهای شناختی مغز انسان"
task = """یک مقاله‌ی علمی درباره‌ی کاربرد شبکه‌های عصبی مصنوعی در مدل‌سازی فرآیندهای شناختی مغز انسان بنویس.
مقاله باید شامل بخش‌های زیر باشد:

- مقدمه: تعریف علوم اعصاب شناختی و اهمیت مدل‌سازی شناخت با استفاده از هوش مصنوعی
- معرفی مدل‌های شبکه‌ی عصبی: معرفی RNN، LSTM، و Transformer و نحوه‌ی شباهت آن‌ها با مغز
- مدل‌سازی کارکردهای شناختی:
   - حافظه‌ی کاری با LSTM
   - توجه انتخابی با مکانیزم attention
   - تصمیم‌گیری با یادگیری تقویتی
- مزایا و چالش‌ها:
   - مزایا: تطبیق‌پذیری بالا، یادگیری غیرخطی، شباهت عملکردی با مغز
   - چالش‌ها: تفسیرناپذیری، تفاوت ساختار زیستی با معماری شبکه‌ها، نیاز به داده‌ی زیاد
- نتیجه‌گیری: خلاصه‌ی نکات کلیدی و آینده‌ی تعامل بین علوم اعصاب و هوش مصنوعی

**توجه:** مقاله باید شامل فهرست منابع یا ارجاع به منابع باشد.

"""

formatted_prompt_3_2 = prompt.format(field=field, topic=topic, task=task)

response_3_2 = llm.invoke(formatted_prompt_3_2)
print(response_3_2.content)

"""---

## مقایسه پرامپت های فارسی

---

**1- در پرامپت اول که بصورت عادی نوشته شده است خروجی بدون فرمت خاصی و فقط بر اساس اطلاعات کمی که به مدل دادیم نوشته شده است اما در پرامپت اول که با استفاده از تعریف متغییر ها نوشته شده است کمی دقیق تر و هر تیتر عنوان های مناسبی دارد**


**2- در پرامپت دوم که بصورت عادی نوشته شده است، میایم تیتر هارو مشخص میکنیم براش م به وضوح میگیم که باید ساختاری که به ما تحویل میدی اینجوری باشه اما باز هم با اینکه تیتر هارو مشخص میکنیم بصورت کامل نمیگیم به چه مواردی اشاره جزئی کن. همین باعث میشه مقاله مارو بر اساس تیتر های که گفتیم بنویسه اما در پرامت دوم که با تعریف متغییر ها نوشته شده به وضوح منظم تر و بار رعایت دقیق ساختاری که بهش دادیم اجرا شده**

**3-اما در نهایت در پرامپت سوم که بصورت ساده نوشته شده است ما ابتدا برای مدل علاوه بر مشخص کرد تیتر هایی که میخواهیم در خروجی مقاله به ما نشان دهد، بهش جهت دهی میدیم و برای هر تیتر جزئیاتی که میخوایم در خروجی نشان بدهد را مشخص میکنیم در پرامت سوم که با مشخص کردن متغییر ها نوشته شده است علاوه بر رعایت تیر های و جزئیاتی که برایش تعریف کردیم، مدل از اضافه گویی های زیاد از حد هم پرهیز کره است**

---

**First exercise with prompts in English**

***According to my field of study, which is Cognitive Science, my chosen topic is as follows:***

**Application of Artificial Neural Networks in Modeling Cognitive Processes of the Human Brain**

---

### Template 1

**Prompt 1 - General and without details**

####The prompts, topic, and main task in template 1 are defined normally and in sequence.
"""

Template_1_1 = """
Assume you are a professional scientific writer with expertise in neuroscience and artificial intelligence.
Your task is to write an article on the following topic:

Topic: The Application of Artificial Neural Networks in Modeling Human Brain Cognitive Processes

Prompt:
Write an article about the application of artificial neural networks in modeling human brain cognitive processes.
"""

prompt_1_1 = PromptTemplate.from_template(Template_1_1)

formatted_promp_1_1 = prompt_1_1.format()

response_1_1 = llm.invoke(formatted_promp_1_1)
print(response_1_1.content)

"""**Prompt 1 - This time we write the first prompt by defining variables to separate the prompts**"""

Template_1_2 = """
Assume you are a professional scientific writer with expertise in {field}.
Your task is to write an article on the following topic:

Topic: {topic}

Prompt:
{task}
"""

prompt_1_2 = PromptTemplate(
    input_variables=["field", "topic", "task"],
    template=Template_1_2
)

field = "neuroscience and artificial intelligence"
topic = "The Application of Artificial Neural Networks in Modeling Human Brain Cognitive Processes"
task = "Write an article about the application of artificial neural networks in modeling human brain cognitive processes."

formatted_prompt_1_2 = prompt_1_2.format(field=field, topic=topic, task=task)

print(formatted_prompt_1_2)

response_1_2 = llm.invoke(formatted_prompt_1_2)
print(response_1_2.content)

"""### Template 2

####The prompts, topic, and main task in template 2 are defined normally and in sequence.

**Prompt 2 - By specifying the main parts of each prompt**
"""

Template_2_1 = """
Assume you are a professional scientific writer with expertise in neuroscience and artificial intelligence.
Your task is to write an article on the following topic:

Topic: The Application of Artificial Neural Networks in Modeling Human Brain Cognitive Processes

Prompt:
Write a scientific article about the application of artificial neural networks in modeling human brain cognitive processes.
The article must include the following sections:
- Introduction
- Overview of Different Types of Artificial Neural Networks
- How Cognitive Processes Are Modeled
- Advantages and Limitations
- Conclusion


"""

prompt_2_1 = PromptTemplate.from_template(Template_2_1)

formatted_prompt_2_1 = prompt_2_1.format()

response_2_1 = llm.invoke(formatted_prompt_2_1)
print(response_2_1.content)

"""**Prompt 2 - This time we write the second prompt by defining variables to separate the prompts**"""

Template_2_2 = """
Assume you are a professional scientific writer with expertise in {field}.
Your task is to write an article on the following topic:

Topic: {topic}

Prompt: {task}
"""

prompt_2_2 = PromptTemplate(
    input_variables=["field", "topic", "task"],
    template=Template_2_2
)

field = "neuroscience and artificial intelligence"
topic = "The Application of Artificial Neural Networks in Modeling Human Brain Cognitive Processes"
task = """Write a scientific article about the application of artificial neural networks in modeling human brain cognitive processes.
The article must include the following sections:
- Introduction
- Overview of Different Types of Artificial Neural Networks
- How Cognitive Processes Are Modeled
- Advantages and Limitations
- Conclusion

"""

formatted_prompt_2_2 = prompt_2_2.format(field=field, topic=topic, task=task)

response_2_2 = llm.invoke(formatted_prompt_2_2)
print(response_2_2.content)

"""### Template 3

####The prompts, topic, and main task in template 3 are defined normally and in sequence.

**Prompt 3 - with much more detail and defining and specifying the title of each title to explain the model**
"""

Template_3_1 = """
Assume you are a professional scientific writer with expertise in neuroscience and artificial intelligence.
Your task is to write an article on the following topic:

Topic: The Application of Artificial Neural Networks in Modeling Human Brain Cognitive Processes


Prompt:
Write a scientific article about the application of artificial neural networks in modeling human brain cognitive processes.
The article must include the following sections:

- Introduction: Define cognitive neuroscience and explain the importance of modeling cognition using AI.
- Overview of Neural Network Models: Introduce RNN, LSTM, and Transformer models and explain how they resemble brain functions.
- Modeling Cognitive Functions:
   - Working memory with LSTM
   - Selective attention using attention mechanisms
   - Decision-making using reinforcement learning
- Advantages and Challenges:
   - Advantages: high adaptability, nonlinear learning, functional similarity to the brain
   - Challenges: lack of interpretability, differences between biological structures and network architectures, high data requirements
- Conclusion: Summarize the key points and future of AI-neuroscience integration

**Note:** The article should include a list of references or citations.
"""

prompt_3_1 = PromptTemplate.from_template(Template_3_1)

formatted_prompt_3_1 = prompt_3_1.format()

response_3_1 = llm.invoke(formatted_prompt_3_1)
print(response_3_1.content)

"""**Prompt 3 - This time we write the second prompt by defining variables to separate the prompts**"""

Template_3_2 = """
Assume you are a professional scientific writer with expertise in {field}.
Your task is to write an article on the following topic:

Topic: {topic}

Prompt: {task} """

prompt_3_2 = PromptTemplate(
    input_variables=["field", "topic", "task"],
    template=template_3_2
)

field = "neuroscience and artificial intelligence"
topic = "The Application of Artificial Neural Networks in Modeling Human Brain Cognitive Processes"
task = """Write a scientific article about the application of artificial neural networks in modeling human brain cognitive processes.
The article must include the following sections:

- Introduction: Define cognitive neuroscience and explain the importance of modeling cognition using AI
- Overview of Neural Network Models: Introduce RNN, LSTM, and Transformer models and explain how they resemble brain functions
- Modeling Cognitive Functions:
   - Working memory with LSTM
   - Selective attention using the attention mechanism
   - Decision-making through reinforcement learning
- Advantages and Challenges:
   - Advantages: high adaptability, nonlinear learning, functional similarity to the brain
   - Challenges: lack of interpretability, differences between biological structures and artificial networks, large data requirements
- Conclusion: Summarize key insights and the future of neuroscience-AI integration

**Note:** The article must include references or citations.
"""

formatted_prompt_3_2 = prompt_3_2.format(field=field, topic=topic, task=task)

response_3_2 = llm.invoke(formatted_prompt_3_2)
print(response_3_2.content)

"""---

### Comparison of English prompts

---

**1- In the first prompt, which is written normally, the output is written without any special format and only based on the little information we gave to the model. However, in the first prompt, which is written using the definition of variables, it is a little more precise and each title has appropriate titles.**

**2- In the second prompt, which is written normally, we come to specify the titles and clearly tell them that the structure you deliver to us should be like this, but again, even though we specify the titles, we do not say in full what items to mention in detail. This makes our article based on the headlines we said, but in the second prompt, which is written with the definition of variables, it is executed more clearly and systematically, strictly observing the structure we gave it**

**3-But finally, in the third prompt, which is written simply, we first give the model direction in addition to specifying the headlines we want it to show us in the article output, and for each headline, we specify the details we want it to show in the output. In the third prompt, which is written with the definition of variables, in addition to observing the arrows and details we defined for it, the model also avoids excessive exaggeration**
"""